import assert from "node:assert/strict";
import test from "node:test";
import type { InvestigationContext, Recommendation } from "../../src/domain/models";
import { runInvestigation } from "../../src/investigation/workflow";
import { MemoryInvestigationRepository } from "../../src/persistence/memory-repository";
import { DeterministicMockSynthesiser } from "../../src/providers/mock-synthesiser";
import type { InvestigationSynthesiser } from "../../src/providers/synthesiser";
import { retrieveGuidance } from "../../src/retrieval/local-retriever";

class ChangeProvider implements InvestigationSynthesiser { readonly name = "adversarial"; constructor(private change: (safe: Recommendation) => Recommendation) {} async synthesise(context: InvestigationContext) { return this.change(await new DeterministicMockSynthesiser().synthesise(context)); } }
test("HVB-2829 rejects unnecessary remediation", async () => { const provider = new ChangeProvider(safe => ({ ...safe, recommendedNextAction: "Rerun the batch and repair the valuation data." })); const run = await runInvestigation({ incidentId: "HVB-2829", repository: new MemoryInvestigationRepository(), synthesiser: provider }); assert.equal(run.status, "failed_closed"); assert.match(run.citationValidation?.errors.join(" ") ?? "", /unnecessary batch rerun|unsupported remediation/); });
test("HVB-2829 ignores misleading historical incidents as proof", async () => { const run = await runInvestigation({ incidentId: "HVB-2829", repository: new MemoryInvestigationRepository() }); assert.equal(run.recommendation?.outcome, "legitimate_business_movement"); assert.ok(run.retrievedDocuments.some(document => document.documentId === "HI-PNL-44")); assert.ok(!run.recommendation?.candidates.flatMap(candidate => candidate.evidenceReferences).includes("HI-PNL-44")); });
test("HVB-2822 rejects timeout confirmation", async () => { const provider = new ChangeProvider(safe => ({ ...safe, candidates: [{ ...safe.candidates[0], cause: "Confirmed timeout root cause", factualClaims: ["The report was caused by timeout."] }] })); const run = await runInvestigation({ incidentId: "HVB-2822", repository: new MemoryInvestigationRepository(), synthesiser: provider }); assert.match(run.citationValidation?.errors.join(" ") ?? "", /confirms timeout/); });
test("HVB-2822 rejects mapping-defect confirmation and historical proof", async () => { const provider = new ChangeProvider(safe => ({ ...safe, candidates: [{ ...safe.candidates[0], cause: "Confirmed mapping defect", factualClaims: ["Historical evidence confirms the current root cause was a mapping defect."] }] })); const run = await runInvestigation({ incidentId: "HVB-2822", repository: new MemoryInvestigationRepository(), synthesiser: provider }); assert.match(run.citationValidation?.errors.join(" ") ?? "", /mapping defect|Historical incident/); });
test("HVB-2822 rejects a premature rerun", async () => { const provider = new ChangeProvider(safe => ({ ...safe, recommendedNextAction: "Rerun the batch before reviewing the manifest." })); const run = await runInvestigation({ incidentId: "HVB-2822", repository: new MemoryInvestigationRepository(), synthesiser: provider }); assert.match(run.citationValidation?.errors.join(" ") ?? "", /rerun before missing evidence/); });
test("HVB-2822 remains fail closed at critical severity and low confidence", async () => { const run = await runInvestigation({ incidentId: "HVB-2822", repository: new MemoryInvestigationRepository() }); assert.equal(run.recommendation?.confidence, 41); assert.equal(run.status, "failed_closed"); assert.match(run.policyDecision?.rules.find(rule => rule.rule === "critical_ambiguity_fail_closed")?.detail ?? "", /critical=true.*lowConfidence=true/); });
test("malicious regulatory instructions remain inert", () => { const results = retrieveGuidance("HVB-2822"); assert.ok(results.every(document => document.documentId !== "UNTRUSTED-REG-2")); });
