"use client";
import { useEffect, useState } from "react";
import type { ExecutableIncidentId, InvestigationRun } from "../../src/domain/models";

const ids: ExecutableIncidentId[] = ["HVB-2847", "HVB-2829", "HVB-2822"];
export function ExecutableObservability() {
  const [incidentId, setIncidentId] = useState<ExecutableIncidentId>("HVB-2847"); const [run, setRun] = useState<InvestigationRun | null>(null);
  useEffect(() => { fetch(`/api/investigations?incidentId=${incidentId}`).then(async response => response.ok ? await response.json() as { run: InvestigationRun | null } : null).then(data => setRun(data?.run ?? null)).catch(() => undefined); }, [incidentId]);
  return <><header className="page-head"><div><div className="eyebrow">Observability · Persisted safe trace</div><h1>{run ? `Trace ${run.id.slice(0, 8)} · ${run.incidentId}` : `No ${incidentId} trace yet`}</h1><p>Actual workflow stages, tool outputs, retrieval, validation, policy, and approval state. Secrets and raw stack traces are excluded.</p></div><select className="select" aria-label="Select executable trace" value={incidentId} onChange={event => { setRun(null); setIncidentId(event.target.value as ExecutableIncidentId); }}>{ids.map(id => <option key={id}>{id}</option>)}</select></header>
    <div className="trace-summary"><div className="metric"><span>Disposition</span><strong>{run?.policyDecision?.result ?? "—"}</strong><small>{run?.policyDecision?.permittedApprovalScope ?? "no run"}</small></div><div className="metric"><span>Provider</span><strong>{run?.provider ?? "—"}</strong><small>no paid API</small></div><div className="metric"><span>Evidence</span><strong>{run?.evidence.length ?? 0}</strong><small>derived records</small></div><div className="metric"><span>Approval</span><strong>{run?.approval?.decision ?? "pending"}</strong><small>{run?.approval?.scope ?? "demo identity"}</small></div></div>
    <section className="trace-card"><div className="trace-head"><span>SPAN</span><span>TYPE</span><span>TIMELINE</span><span>DURATION</span><span>RESULT</span></div>{run?.toolExecutions.map((tool, index) => <div className="trace-row" key={tool.id}><code>{tool.toolName}</code><span className={`tag ${tool.status === "failed" ? "tag-red" : tool.status === "warning" ? "tag-amber" : "tag-green"}`}>Deterministic</span><i><b style={{ marginLeft: `${Math.min(index * 6, 55)}%`, width: `${Math.max(8, 34 - index * 2)}%` }} /></i><span>{tool.durationMs}ms</span><strong>{tool.status}</strong></div>)}{run?.auditEvents.filter(event => event.eventType !== "tools.completed").map(event => <div className="trace-row" key={event.id}><code>{event.eventType}</code><span className="tag tag-blue">Workflow</span><i><b style={{ width: "18%" }} /></i><span>recorded</span><strong>✓</strong></div>)}</section>
    {run ? <div className="safe-prompt"><span>RETRIEVAL + POLICY</span><p>{run.retrievedDocuments.map(document => `${document.documentId} (${document.trust}, score ${document.relevanceScore})`).join(" · ")} · Citation validation: {run.citationValidation?.valid ? "pass" : "fail"} · Policy: {run.policyDecision?.result}</p><span className="tag tag-green">Persisted</span></div> : <div className="safe-prompt"><span>NO TRACE</span><p>Run {incidentId} from the investigation workspace to create a persisted trace.</p></div>}
  </>;
}
