"use client";

import { useEffect, useMemo, useState } from "react";
import type { InvestigationRun, Recommendation } from "../../src/domain/models";
import { incidents, type Incident } from "../data";

type Tab = "evidence" | "diagnosis" | "recommendation" | "approval" | "remediation" | "validation" | "audit";
function Tag({ children, tone = "slate" }: { children: React.ReactNode; tone?: string }) { return <span className={`tag tag-${tone}`}>{children}</span>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><i>◇</i><h3>{title}</h3><p>{text}</p></div>; }
function Cites({ ids, open }: { ids: string[]; open: () => void }) { return <>{ids.map(id => <button className="citation" key={id} onClick={open}>[{id}]</button>)}</>; }
function List({ items }: { items: string[] }) { return <ul className="rec-list">{items.map(item => <li key={item}>{item}</li>)}</ul>; }

function Diagnosis({ recommendation, openEvidence }: { recommendation: Recommendation; openEvidence: () => void }) {
  const facts = recommendation.observedFacts ?? [];
  const probable = recommendation.candidates.filter(item => item.status === "probable_root_cause");
  const hypotheses = recommendation.candidates.filter(item => !item.status || item.status === "hypothesis");
  const ruledOut = recommendation.candidates.filter(item => item.status === "ruled_out");
  return <div className="diagnosis-grid">
    <section><span>OBSERVED FACTS</span>{facts.length ? facts.map(item => <article key={item.fact}><p>{item.fact} <Cites ids={item.evidenceReferences} open={openEvidence} /></p></article>) : <p className="muted">The initial evidence packet is incomplete; the workflow will not convert signals into facts it cannot support.</p>}</section>
    <section><span>HYPOTHESES BEING TESTED</span>{hypotheses.map(item => <article key={item.cause}><h3>{item.cause}</h3><p>{item.rationale || item.factualClaims.join(" ")} <Cites ids={item.evidenceReferences} open={openEvidence} /></p><Tag tone="amber">{item.confidence}% · hypothesis</Tag></article>)}</section>
    <section className="probable"><span>PROBABLE ROOT CAUSE</span>{probable.length ? probable.map(item => <article key={item.cause}><h3>{item.cause}</h3><p>{item.rationale}</p><Tag tone="green">{item.confidence}% · evidence supported</Tag></article>) : <article><h3>Not established</h3><p>{recommendation.uncertaintyExplanation}</p><Tag tone="red">{recommendation.confidence}% · fail closed</Tag></article>}</section>
    <section><span>RULED-OUT CAUSES</span>{ruledOut.length ? ruledOut.map(item => <article key={item.cause}><h3>{item.cause}</h3><p>{item.rationale} <Cites ids={item.evidenceReferences} open={openEvidence} /></p></article>) : <p className="muted">No cause is ruled out until current evidence contradicts it.</p>}</section>
  </div>;
}

export function ExecutableInvestigation({ incident, selectIncident }: { incident: Incident; selectIncident: (incident: Incident) => void }) {
  const [run, setRun] = useState<InvestigationRun | null>(null);
  const [tab, setTab] = useState<Tab>("evidence");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const flagship = incident.id === "HVB-2847";
  const progressiveCritical = incident.id === "HVB-2822";
  const supportsRemediation = flagship || progressiveCritical;
  useEffect(() => { fetch(`/api/investigations?incidentId=${incident.id}`).then(async response => response.ok ? await response.json() as { run: InvestigationRun | null } : null).then(data => setRun(data?.run ?? null)).catch(() => undefined); }, [incident.id]);
  const evidence = useMemo(() => [
    ...(run?.evidence ?? []),
    ...(run?.retrievedDocuments ?? []).map(document => ({ id: document.documentId, kind: "runbook", title: document.title, detail: document.excerpt, source: `${document.trust} · v${document.version}`, signal: "supports" as const, observedAt: run?.completedAt ?? run?.startedAt ?? "", relevance: `Retrieved guidance · relevance score ${document.relevanceScore}` })),
  ], [run]);
  const recommendation = run?.recommendation;
  const initialFailClosed = run?.status === "failed_closed";
  const resolved = run?.status === "resolved";
  const supplemental = Boolean(run?.toolExecutions.some(item => item.toolName === "interface.delivery"));

  async function execute() {
    setLoading(true); setError("");
    try { const response = await fetch("/api/investigations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ incidentId: incident.id }) }); const data = await response.json() as { run?: InvestigationRun; error?: string }; if (!response.ok) throw new Error(data.error ?? "Investigation failed."); setRun(data.run!); setTab(supportsRemediation ? "diagnosis" : "recommendation"); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Investigation failed safely."); } finally { setLoading(false); }
  }
  async function decide(decision: "approved" | "rejected" | "request_more_investigation") {
    if (!run) return; setLoading(true); setError("");
    try { const response = await fetch("/api/approvals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ runId: run.id, decision, scope: initialFailClosed ? "escalation_disposition" : "recommendation", comment: decision === "request_more_investigation" ? "Cause is not supported; collect the missing current evidence." : "Reviewed evidence, risk, blast radius, preconditions, validation, and rollback in the synthetic demonstration." }) }); const data = await response.json() as { run?: InvestigationRun; error?: string }; if (!response.ok) throw new Error(data.error ?? "Decision rejected."); setRun(data.run!); setTab(decision === "request_more_investigation" ? "diagnosis" : decision === "approved" && supportsRemediation ? "remediation" : "audit"); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Decision rejected safely."); } finally { setLoading(false); }
  }
  async function remediate() {
    if (!run) return; setLoading(true); setError("");
    const actionId = incident.id === "HVB-2847" ? "refresh_fx_market_data_and_rerun_risk_controls" : "reingest_liquidity_segment_and_resume_datamart";
    try { const response = await fetch("/api/remediations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ runId: run.id, actionId, confirmSynthetic: true }) }); const data = await response.json() as { run?: InvestigationRun; error?: string }; if (!response.ok) throw new Error(data.error ?? "Synthetic recovery rejected."); setRun(data.run!); setTab("validation"); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Synthetic recovery rejected safely."); } finally { setLoading(false); }
  }

  const stages = supportsRemediation ? ["Incident", "Investigate", "Evidence", "Diagnosis", "Recommend", "Approve", "Remediate", "Validate", "Audit"] : ["Validate", "Gather", "Retrieve", "Synthesize", "Approve", "Record"];
  return <>
    <header className="page-head"><div><div className="eyebrow">{flagship ? "Flagship workflow · 5–7 minute bank incident demo" : "Shared executable workflow"}</div><h1>{flagship ? "Controlled Murex incident recovery" : "Exception investigation"}</h1><p>{flagship ? "Evidence before inference. Approval before action. Validation before closure." : "Deterministic controls, local retrieval, cited synthesis, persistence, and human disposition."}</p></div><div className="head-actions"><select aria-label="Select incident" value={incident.id} onChange={event => selectIncident(incidents.find(item => item.id === event.target.value)!)} className="select">{incidents.map(item => <option key={item.id}>{item.id}</option>)}</select><button className="primary" onClick={execute} disabled={loading}>{loading ? "Working safely…" : run ? "Restart investigation" : "Start investigation"}</button></div></header>
    {error && <div className="error-banner"><strong>Safe stop</strong><span>{error}</span></div>}
    {supportsRemediation && <div className="synthetic-banner"><strong>SYNTHETIC PROD-SIM</strong><span>No Westpac, bank, or real Murex infrastructure is connected. Recovery execution is a deterministic simulation.</span><Tag tone="amber">Write scope: simulator only</Tag></div>}
    <div className="context-strip"><div><span>INCIDENT</span><strong>{incident.id}</strong></div><div><span>ENVIRONMENT</span><strong>{supportsRemediation ? "PROD-SIM" : "Synthetic"}</strong></div><div><span>SEVERITY</span><Tag tone={incident.severity === "Critical" ? "red" : "amber"}>{incident.severity}</Tag></div><div><span>{flagship ? "REPORT DISTRIBUTION" : "INTERNAL SIGN-OFF"}</span><strong>{flagship ? "HELD · 14:00 review" : progressiveCritical ? "14:00 AEST · at risk" : incident.businessDate}</strong></div><div><span>STATE</span><Tag tone={resolved ? "green" : run?.status === "requires_escalation" ? "red" : initialFailClosed ? "red" : run ? "blue" : "slate"}>{resolved ? "Resolved + validated" : run?.status === "requires_escalation" ? "Validation failed · escalated" : run?.status ?? "Not started"}</Tag></div></div>
    <section className="incident-summary"><div><div className="row-title"><h2>{incident.title}</h2><Tag tone={resolved ? "green" : "blue"}>{resolved ? "Closed" : incident.status}</Tag></div><p>{incident.description}</p></div><div className="impact"><span>Business impact</span><strong>{flagship ? "AUD 12.8m USD/JPY-sensitive exposure under review; Daily Market Risk distribution held until refreshed controls pass." : progressiveCritical ? "Liquidity Coverage Pack blocked; Regulatory Reporting sign-off window at risk; report distribution held." : incident.impact}</strong></div></section>
    <div className={`stepper ${supportsRemediation ? "stepper-nine" : ""}`} aria-label="Investigation stages">{stages.map((step, index) => <div key={step} className={resolved || run?.status === "requires_escalation" || (run && (supplemental || index < 4)) ? "done" : ""}><i>{index + 1}</i><span>{step}</span></div>)}</div>
    <div className="workspace-grid"><aside className="control-panel"><div className="panel-title"><span>EVIDENCE & CONTROL RUN</span><Tag tone={resolved ? "green" : initialFailClosed ? "red" : run ? "blue" : "slate"}>{run?.status ?? "Not run"}</Tag></div>
      {run ? run.toolExecutions.map(tool => <div className="control-row" key={tool.id}><i className={tool.status === "passed" ? "ok-dot" : tool.status === "warning" ? "warn-dot" : "error-dot"}></i><div><span>{tool.toolName}</span><strong>{tool.status} · {tool.evidenceIds.length} cited record{tool.evidenceIds.length === 1 ? "" : "s"}</strong></div></div>) : <div className="control-row"><i className="pending-dot"></i><div><span>Server workflow</span><strong>Awaiting execution</strong></div></div>}
      <div className="boundary-note"><span>ACTION BOUNDARY</span><p>{run?.approval?.decision === "approved" ? "A recommendation is approved, but only the explicit synthetic recovery endpoint can act." : "Read-only investigation. No trade, market data, Datamart, batch, file-transfer, or report mutation is permitted."}</p></div>
      {flagship && <div className="roi-mini"><span>ILLUSTRATIVE ASSUMPTIONS</span><div><b>Manual investigation</b><strong>94 min</strong></div><div><b>AI-assisted diagnosis</b><strong>18 min</strong></div><div><b>Engineer time saved</b><strong>76 min</strong></div><div><b>Sources correlated</b><strong>5</strong></div><small>Scenario assumptions only · not measured ROI or an industry benchmark</small></div>}
    </aside><section className="main-panel"><div className="tabs">{(["evidence", "diagnosis", "recommendation", "approval", "remediation", "validation", "audit"] as Tab[]).filter(item => supportsRemediation || !["diagnosis", "remediation", "validation"].includes(item)).map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}{item === "evidence" && <b>{evidence.length}</b>}</button>)}</div>
      {tab === "evidence" && (evidence.length ? <div className="evidence-list">{evidence.map(item => <article key={item.id}><div className="evidence-icon">{item.kind.slice(0, 1).toUpperCase()}</div><div><div className="evidence-meta"><Tag tone={item.signal === "contradicts" ? "red" : item.signal === "supports" ? "green" : "slate"}>{item.signal}</Tag><span>{item.id} · {item.kind}</span></div><h3>{item.title}</h3><p>{item.detail}</p><small>Source: {item.source} · {item.observedAt ? new Date(item.observedAt).toLocaleString() : "retrieved"}</small><small className="relevance">Why relevant: {item.relevance}</small></div></article>)}</div> : <Empty title="No executed evidence yet" text={`Start ${incident.id} to collect timestamped evidence from structured synthetic inputs.`} />)}
      {tab === "diagnosis" && (!recommendation ? <Empty title="No diagnosis yet" text="The evidence workflow must run before any hypothesis is ranked." /> : <Diagnosis recommendation={recommendation} openEvidence={() => setTab("evidence")} />)}
      {tab === "recommendation" && (!recommendation ? <Empty title="No cited recommendation yet" text="Validation, tools, retrieval, synthesis, citation checks, and policy must complete first." /> : <div className="recommendation"><div className="rec-head"><div><span>RECOMMENDATION V{recommendation.version} · {run?.provider}</span><h2>{initialFailClosed ? "No remediation recommendation — evidence insufficient" : recommendation.candidates.find(item => item.status === "probable_root_cause")?.cause ?? recommendation.candidates[0].cause}</h2></div><div className={`confidence ${initialFailClosed ? "low" : ""}`}><strong>{recommendation.confidence}%</strong><span>{initialFailClosed ? "insufficient" : "high confidence"}</span></div></div><div className="claim"><span>DIAGNOSIS</span><p>{recommendation.diagnosis || recommendation.analystSummary} <Cites ids={recommendation.candidates[0].evidenceReferences} open={() => setTab("evidence")} /></p></div><div className="claim"><span>RECOMMENDED ACTION</span><p>{recommendation.recommendedNextAction} <Cites ids={recommendation.actionEvidenceReferences} open={() => setTab("evidence")} /></p></div>{recommendation.risk && <div className="rec-detail-grid"><div><span>RISK</span><p>{recommendation.risk}</p></div><div><span>BLAST RADIUS</span><p>{recommendation.blastRadius}</p></div><div><span>PRECONDITIONS</span><List items={recommendation.preconditions ?? []} /></div><div><span>VALIDATION</span><List items={recommendation.validationPlan ?? []} /></div><div className="wide"><span>ROLLBACK</span><p>{recommendation.rollbackPlan}</p></div></div>}<div className="guardrail"><strong>Confidence rationale</strong><p>{recommendation.confidenceRationale || recommendation.uncertaintyExplanation}</p></div><button className="primary" onClick={() => setTab("approval")}>{initialFailClosed ? "Review safe next step" : "Review approval packet"}</button></div>)}
      {tab === "approval" && (!run?.policyDecision || !recommendation ? <Empty title="No decision packet" text="Complete the investigation first." /> : <div className="approval"><div className="approval-banner"><i>!</i><div><strong>{initialFailClosed ? "Approval is blocked; more evidence is required" : "Human approval is a real execution boundary"}</strong><p>{initialFailClosed ? "The current recommendation cannot be approved as a resolution. Request more investigation or reject it." : "The reviewer sees the same evidence snapshot, action scope, risk, blast radius, preconditions, validation, and rollback that execution will enforce."}</p></div></div><dl><div><dt>Reviewer</dt><dd>demo.support.analyst · synthetic Production Support role</dd></div><div><dt>Proposed action</dt><dd>{recommendation.recommendedNextAction}</dd></div><div><dt>Risk / blast radius</dt><dd>{recommendation.risk || recommendation.uncertaintyExplanation} {recommendation.blastRadius}</dd></div><div><dt>Evidence snapshot</dt><dd>{run.citationValidation?.checkedEvidenceIds.join(", ")}</dd></div><div><dt>Policy result</dt><dd>{run.policyDecision.result} · scope: {run.policyDecision.permittedApprovalScope} · operational effect before approval: none</dd></div></dl>{run.approval ? <div className={`decision-record ${run.approval.decision}`}><strong>Recommendation {run.approval.decision}</strong><span>{run.approval.identity} · {new Date(run.approval.decidedAt).toLocaleString()} · {run.approval.comment}</span></div> : <div className="decision-actions">{initialFailClosed ? <button className="primary" disabled={loading} onClick={() => decide("request_more_investigation")}>Request more investigation</button> : <button className="primary" disabled={loading} onClick={() => decide("approved")}>Approve scoped synthetic recovery</button>}<button className="secondary danger" disabled={loading} onClick={() => decide("rejected")}>Reject</button></div>}</div>)}
      {tab === "remediation" && (!run?.approval || run.approval.decision !== "approved" ? <Empty title="Remediation locked" text="A supported recommendation and recorded human approval are required. No bypass exists." /> : <div className="remediation"><div className="synthetic-action"><Tag tone="amber">SIMULATED / SYNTHETIC REMEDIATION</Tag><h2>{flagship ? "Approved FX refresh and scoped risk rerun" : "Scoped segment recovery"}</h2><p>{run.remediation?.action ?? (flagship ? "Refresh the approved synthetic USD/JPY observation, rerun only the affected APAC market-data and risk controls, then reconcile before releasing the report hold." : "Re-ingest only LIQ_POS_14.csv, resume the LCR Datamart chain from SOURCE_READER, and run every downstream control.")}</p></div>{run.remediation ? <>{run.remediation.preconditions.map(item => <div className="remediation-step" key={item.check}><i>{item.passed ? "✓" : "!"}</i><div><strong>Precondition · {item.check}</strong><span>{item.detail}</span></div></div>)}{run.remediation.steps.map(step => <div className="remediation-step" key={step.order}><i>✓</i><div><strong>{step.order}. {step.action}</strong><span>{step.result}</span></div></div>)}<button className="primary" onClick={() => setTab("validation")}>Inspect post-action validation</button></> : <><div className="guardrail"><strong>Approved — Ready for simulated remediation</strong><p>Recommendation v{run.approval.recommendationVersion} approved by {run.approval.identity} at {new Date(run.approval.decidedAt).toLocaleString()}. Execution is limited to the allow-listed action; the simulator cannot run arbitrary commands, SQL, APIs, or code.</p></div><button className="primary" disabled={loading} onClick={remediate}>Execute approved synthetic recovery</button></>}</div>)}
      {tab === "validation" && (!run?.remediation ? <Empty title="No post-action evidence" text="Execution success is not resolution. Run the approved simulation, then validate every downstream outcome." /> : <div className="validation"><div className="validation-head"><div><span>POST-ACTION VALIDATION · DETERMINISTIC</span><h2>{run.remediation.resolution.outcome === "RESOLVED" ? "Resolved only after controls pass" : "Validation failed — incident escalated"}</h2></div><Tag tone={run.remediation.resolution.outcome === "RESOLVED" ? "green" : "red"}>{run.remediation.validation.filter(item => item.passed).length} / {run.remediation.validation.length} passed</Tag></div>{run.remediation.validation.map(item => <div className="validation-row" key={item.control}><strong>{item.control}</strong><span className="before">{item.before}</span><i>→</i><span className="after">{item.after}</span><Tag tone={item.passed ? "green" : "red"}>{item.passed ? "passed" : "failed"}</Tag></div>)}<div className="guardrail"><strong>Outcome · {run.remediation.resolution.outcome}</strong><p>{run.remediation.resolution.detail} The model cannot override this state.</p></div><button className="primary" onClick={() => setTab("audit")}>Review complete audit trail</button></div>)}
      {tab === "audit" && <div className="audit"><div className="audit-head"><h3>Persisted append-only activity record</h3><Tag tone="green">Inputs · actor · outcome</Tag></div>{run?.auditEvents.length ? run.auditEvents.map(event => <div key={event.id}><span>{String(event.sequence).padStart(2, "0")}</span><p>{new Date(event.occurredAt).toLocaleTimeString()} · {event.summary}<small>Actor: {String(event.metadata.actor ?? (event.eventType.startsWith("approval") ? "demo.support.analyst" : "workbench.orchestrator"))} · Evidence/input: {String(event.metadata.evidenceIds ?? event.metadata.incidentId ?? event.metadata.outcome ?? "recorded snapshot")}</small></p><code>{event.eventType}</code></div>) : <Empty title="No persisted activity yet" text="Every investigation, evidence, decision, action, validation, and closure event appears here." />}</div>}
    </section></div>
  </>;
}
