"use client";
import { useEffect, useState } from "react";
import type { EvaluationResult } from "../../src/domain/models";

export function ExecutableEvaluation() {
  const [result, setResult] = useState<EvaluationResult | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/evaluations").then(async response => response.ok ? await response.json() as { result: EvaluationResult | null } : null).then(data => data?.result && setResult(data.result)).catch(() => undefined); }, []);
  async function run() { setLoading(true); setError(""); try { const response = await fetch("/api/evaluations", { method: "POST" }); const data = await response.json() as { result?: EvaluationResult; error?: string }; if (!response.ok && !data.result) throw new Error(data.error); setResult(data.result!); } catch { setError("Evaluation stopped safely; no measured result was recorded."); } finally { setLoading(false); } }
  return <><header className="page-head"><div><div className="eyebrow">Stage 4 · Evaluate · One executable case</div><h1>Evidence before confidence</h1><p>HVB-2847 runs through the same persisted production workflow as the investigation screen. The 30-case suite remains roadmap.</p></div><button className="primary" disabled={loading} onClick={run}>{loading ? "Running golden case…" : "Run HVB-2847 golden case"}</button></header>{error && <div className="error-banner">{error}</div>}
    <div className="eval-banner"><div><span>{result ? `MEASURED RUN · ${new Date(result.executedAt).toLocaleString()}` : "NO MEASURED RUN YET"}</span><strong>{result ? `1 / 1 executable case ${result.passed ? "passed" : "failed"}` : "Run the executable case to establish evidence"}</strong></div><span className={`tag ${result?.passed ? "tag-green" : "tag-amber"}`}>{result ? (result.passed ? "Measured pass" : "Measured failure") : "Awaiting run"}</span></div>
    <div className="eval-grid">{Object.entries(result?.scores ?? { deterministicToolCorrectness: 0, citationValidity: 0, policyCorrectness: 0, summaryCompleteness: 0 }).map(([label, score]) => <div className={`metric ${result ? "greenline" : ""}`} key={label}><span>{label.replace(/([A-Z])/g, " $1")}</span><strong>{result ? `${Math.round(score * 100)}%` : "—"}</strong><small>{result ? "measured · HVB-2847" : "not measured"}</small></div>)}</div>
    <div className="eval-bottom"><section className="bar-card"><h3>Measured case-level checks</h3>{Object.entries(result?.scores ?? {}).map(([name, score]) => <div className="bar" key={name}><span>{name.replace(/([A-Z])/g, " $1")}</span><i><b style={{ width: `${score * 100}%` }} /></i><strong>{Math.round(score * 100)}%</strong></div>)}{!result && <p className="muted-copy">No benchmark values are shown as measured until the executable action completes.</p>}</section><section className="failure-card"><h3>30-case dashboard roadmap</h3><div><span>○</span><p>Additional incident classes</p><strong>Planned</strong></div><div><span>○</span><p>Model configuration comparison</p><strong>Planned</strong></div><div><span>○</span><p>Acceptance and timing baselines</p><strong>Planned</strong></div><small>Previous static “30/30” claims have been removed. Illustrative portfolio designs are not evaluation evidence.</small></section></div>
  </>;
}
