"use client";
import { useEffect, useState } from "react";
import type { InvestigationRun } from "../../src/domain/models";

export function ExecutableObservability() {
  const [run, setRun] = useState<InvestigationRun | null>(null);
  useEffect(() => { fetch("/api/investigations?incidentId=HVB-2847").then(async response => response.ok ? await response.json() as { run: InvestigationRun | null } : null).then(data => data?.run && setRun(data.run)).catch(() => undefined); }, []);
  return <><header className="page-head"><div><div className="eyebrow">Observability · Persisted safe trace</div><h1>{run ? `Trace ${run.id.slice(0, 8)} · HVB-2847` : "No executable trace yet"}</h1><p>Actual workflow stages, tool outputs, retrieval, validation, policy, and approval state. Secrets and raw stack traces are excluded.</p></div></header>
    <div className="trace-summary"><div className="metric"><span>Disposition</span><strong>{run?.policyDecision?.result ?? "—"}</strong><small>operational effect: none</small></div><div className="metric"><span>Provider</span><strong>{run?.provider ?? "—"}</strong><small>no paid API</small></div><div className="metric"><span>Evidence</span><strong>{run?.evidence.length ?? 0}</strong><small>derived records</small></div><div className="metric"><span>Approval</span><strong>{run?.approval?.decision ?? "pending"}</strong><small>demo identity</small></div></div>
    <section className="trace-card"><div className="trace-head"><span>SPAN</span><span>TYPE</span><span>TIMELINE</span><span>DURATION</span><span>RESULT</span></div>{run?.toolExecutions.map((tool, index) => <div className="trace-row" key={tool.id}><code>{tool.toolName}</code><span className={`tag ${tool.status === "failed" ? "tag-red" : tool.status === "warning" ? "tag-amber" : "tag-green"}`}>Deterministic</span><i><b style={{ marginLeft: `${index * 8}%`, width: `${Math.max(8, 34 - index * 3)}%` }} /></i><span>{tool.durationMs}ms</span><strong>{tool.status}</strong></div>)}{run?.auditEvents.filter(event => !["tools.completed"].includes(event.eventType)).map(event => <div className="trace-row" key={event.id}><code>{event.eventType}</code><span className="tag tag-blue">Workflow</span><i><b style={{ width: "18%" }} /></i><span>recorded</span><strong>✓</strong></div>)}</section>
    {run ? <div className="safe-prompt"><span>RETRIEVAL + POLICY</span><p>{run.retrievedDocuments.map(document => `${document.documentId} (${document.trust}, score ${document.relevanceScore})`).join(" · ")} · Citation validation: {run.citationValidation?.valid ? "pass" : "fail"} · Policy: {run.policyDecision?.result}</p><span className="tag tag-green">Persisted</span></div> : <div className="safe-prompt"><span>NO TRACE</span><p>Run HVB-2847 from the investigation workspace to create a persisted trace.</p></div>}
  </>;
}
