"use client";
import { useEffect, useMemo, useState } from "react";
import type { EvaluationResult } from "../../src/domain/models";

const label = (value: string) => value.replace(/([A-Z])/g, " $1").replace(/^./, char => char.toUpperCase());
export function ExecutableEvaluation() {
  const [results, setResults] = useState<EvaluationResult[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const passed = results.length === 3 && results.every(result => result.passed);
  useEffect(() => { fetch("/api/evaluations").then(async response => response.ok ? await response.json() as { results: EvaluationResult[] } : null).then(data => data?.results && setResults(data.results)).catch(() => undefined); }, []);
  async function run() { setLoading(true); setError(""); try { const response = await fetch("/api/evaluations", { method: "POST" }); const data = await response.json() as { results?: EvaluationResult[]; error?: string }; if (!response.ok && !data.results) throw new Error(data.error); setResults(data.results!); } catch { setError("Evaluation stopped safely; no complete measured suite was recorded."); } finally { setLoading(false); } }
  const averages = useMemo(() => { const names = [...new Set(results.flatMap(result => Object.keys(result.scores)))]; return Object.fromEntries(names.map(name => [name, results.reduce((sum, result) => sum + (result.scores[name] ?? 0), 0) / Math.max(results.length, 1)])); }, [results]);
  return <><header className="page-head"><div><div className="eyebrow">Stage 4 · Evaluate · Three executable cases</div><h1>Evidence before confidence</h1><p>Three distinct outcomes run through the same persisted workflow. The 30-case suite remains roadmap.</p></div><button className="primary" disabled={loading} onClick={run}>{loading ? "Running three golden cases…" : "Run three-case golden suite"}</button></header>{error && <div className="error-banner">{error}</div>}
    <div className="eval-banner"><div><span>{results.length ? `LATEST MEASURED SUITE · ${new Date(Math.max(...results.map(result => Date.parse(result.executedAt)))).toLocaleString()}` : "NO COMPLETE MEASURED SUITE YET"}</span><strong>{results.length ? `${results.filter(result => result.passed).length} / ${results.length} executable cases passed` : "Run all three cases to establish evidence"}</strong></div><span className={`tag ${passed ? "tag-green" : "tag-amber"}`}>{results.length ? (passed ? "Measured pass" : "Measured failure") : "Awaiting run"}</span></div>
    <div className="eval-grid">{results.map(result => <div className={`metric ${result.passed ? "greenline" : "redline"}`} key={result.caseId}><span>{result.incidentId} · {result.caseId}</span><strong>{result.passed ? "PASS" : "FAIL"}</strong><small>{result.outcome} · {result.policyResult}{result.failClosed ? " · failed closed" : ""}</small><small>run {result.investigationId.slice(0, 8)} · {new Date(result.executedAt).toLocaleTimeString()}</small></div>)}</div>
    <div className="eval-bottom"><section className="bar-card"><h3>Measured suite metrics</h3>{Object.entries(averages).map(([name, score]) => <div className="bar" key={name}><span>{label(name)}</span><i><b style={{ width: `${score * 100}%` }} /></i><strong>{Math.round(score * 100)}%</strong></div>)}{!results.length && <p className="muted-copy">No benchmark values are shown as measured until all executable actions complete.</p>}</section><section className="failure-card"><h3>Case evidence and traces</h3>{results.map(result => <div key={result.caseId}><span>{result.passed ? "✓" : "!"}</span><p><a href={`/api/investigations?incidentId=${result.incidentId}`}>{result.incidentId} evidence + trace</a></p><strong>{result.failures.length ? result.failures.join(", ") : "All 17 checks passed"}</strong></div>)}<h3>30-case roadmap</h3><small>Three executable golden cases are measured. The remaining 27-case expansion, provider comparison, and timing baselines are planned—not completed.</small></section></div>
  </>;
}
