import assert from "node:assert/strict";
import test from "node:test";
import { decideApproval, runInvestigation } from "../../src/investigation/workflow";
import { MemoryInvestigationRepository } from "../../src/persistence/memory-repository";

test("HVB-2829 persists an explained no-remediation outcome", async () => { const repository = new MemoryInvestigationRepository(); const run = await runInvestigation({ incidentId: "HVB-2829", repository }); assert.equal(run.status, "completed"); assert.equal(run.recommendation?.outcome, "legitimate_business_movement"); assert.match(run.recommendation?.recommendedNextAction ?? "", /Do not repair data or rerun the batch/i); assert.equal((await repository.getLatestRun("HVB-2829"))?.id, run.id); const decided = await decideApproval({ repository, runId: run.id, decision: "approved" }); assert.equal(decided.approval?.scope, "recommendation"); });
test("HVB-2822 persists a failed-closed critical disposition", async () => { const repository = new MemoryInvestigationRepository(); const run = await runInvestigation({ incidentId: "HVB-2822", repository }); assert.equal(run.status, "failed_closed"); assert.equal(run.recommendation?.outcome, "unconfirmed_critical_cause"); assert.equal(run.policyDecision?.permittedApprovalScope, "escalation_disposition"); assert.equal((await repository.getLatestRun("HVB-2822"))?.id, run.id); });
test("HVB-2822 rejects confirmed-resolution approval but permits escalation disposition", async () => { const repository = new MemoryInvestigationRepository(); const run = await runInvestigation({ incidentId: "HVB-2822", repository }); await assert.rejects(() => decideApproval({ repository, runId: run.id, decision: "approved", scope: "recommendation" }), /confirmed resolution/); const decided = await decideApproval({ repository, runId: run.id, decision: "approved", scope: "escalation_disposition" }); assert.equal(decided.approval?.decision, "approved"); assert.equal(decided.approval?.scope, "escalation_disposition"); assert.match(decided.auditEvents.at(-1)?.summary ?? "", /Escalation disposition approved/); });
test("HVB-2822 permits rejection without confirming a cause", async () => { const repository = new MemoryInvestigationRepository(); const run = await runInvestigation({ incidentId: "HVB-2822", repository }); const decided = await decideApproval({ repository, runId: run.id, decision: "rejected", scope: "escalation_disposition" }); assert.equal(decided.approval?.decision, "rejected"); });
