"use client";

import { useMemo, useState } from "react";
import { evaluationMetrics, incidents, interviews, opportunities, workflow, type Incident } from "./data";

type View = "investigate" | "queue" | "discover" | "diagnose" | "evaluate" | "observe" | "govern" | "value" | "report" | "architecture" | "demo";
type InvestigationState = "ready" | "complete" | "approved" | "rejected";

const nav: { label: string; view: View; kicker: string }[] = [
  { label: "Investigation workspace", view: "investigate", kicker: "Deploy" },
  { label: "Incident queue", view: "queue", kicker: "Deploy" },
  { label: "Workflow & interviews", view: "discover", kicker: "Discover" },
  { label: "Opportunity matrix", view: "diagnose", kicker: "Diagnose" },
  { label: "Evaluation dashboard", view: "evaluate", kicker: "Evaluate" },
  { label: "Observability & traces", view: "observe", kicker: "Evaluate" },
  { label: "Governance controls", view: "govern", kicker: "Control" },
  { label: "ROI & value", view: "value", kicker: "Prove value" },
  { label: "FDE engagement report", view: "report", kicker: "Engagement" },
  { label: "System boundaries", view: "architecture", kicker: "Architecture" },
  { label: "Demo launcher", view: "demo", kicker: "Portfolio" },
];

function Tag({ children, tone = "slate" }: { children: React.ReactNode; tone?: string }) {
  return <span className={`tag tag-${tone}`}>{children}</span>;
}

function Header({ eyebrow, title, text, right }: { eyebrow: string; title: string; text: string; right?: React.ReactNode }) {
  return <header className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div>{right}</header>;
}

function Metric({ label, value, note, tone }: { label: string; value: string; note: string; tone?: string }) {
  return <div className={`metric ${tone || ""}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>;
}

function Investigation({ incident, setIncident, state, setState, audit, setAudit }: { incident: Incident; setIncident: (i: Incident) => void; state: InvestigationState; setState: (s: InvestigationState) => void; audit: string[]; setAudit: (a: string[]) => void }) {
  const [tab, setTab] = useState<"evidence" | "recommendation" | "approval" | "audit">("evidence");
  const run = () => { setState("complete"); setTab("recommendation"); setAudit(["09:14:03 · Payload validated · schema v1.2", "09:14:04 · Deterministic controls completed · 3 checks", "09:14:04 · Local retrieval completed · trusted documents only", "09:14:05 · Recommendation validated · 4 citations", "09:14:05 · Approval gate opened · no action executed"]); };
  const decide = (decision: "approved" | "rejected") => { setState(decision); setTab("audit"); setAudit([...audit, `09:16:22 · Recommendation ${decision} · analyst.s.lee · demo session`]); };
  const failClosed = incident.confidence < 70 || incident.severity === "Critical";
  return <>
    <Header eyebrow="Stage 3 · Deploy" title="Exception investigation" text="Deterministic controls first. AI synthesis second. An accountable human decides." right={<div className="head-actions"><select aria-label="Select incident" value={incident.id} onChange={e => { setIncident(incidents.find(i => i.id === e.target.value)!); setState("ready"); setAudit([]); }} className="select">{incidents.map(i => <option key={i.id}>{i.id}</option>)}</select><button className="primary" onClick={run}>{state === "ready" ? "Run controlled investigation" : "Run again"}</button></div>} />
    <div className="context-strip"><div><span>INCIDENT</span><strong>{incident.id}</strong></div><div><span>REPORT</span><strong>{incident.report}</strong></div><div><span>BUSINESS DATE</span><strong>{incident.businessDate}</strong></div><div><span>OWNER</span><strong>{incident.owner}</strong></div><div><span>SEVERITY</span><Tag tone={incident.severity === "Critical" ? "red" : incident.severity === "High" ? "amber" : "blue"}>{incident.severity}</Tag></div></div>
    <section className="incident-summary"><div><div className="row-title"><h2>{incident.title}</h2><Tag tone="blue">{incident.status}</Tag></div><p>{incident.description}</p></div><div className="impact"><span>Potential impact</span><strong>{incident.impact}</strong></div></section>
    <div className="stepper" aria-label="Investigation stages">{["Validate", "Gather", "Retrieve", "Synthesize", "Approve", "Record"].map((s, idx) => <div key={s} className={(state !== "ready" || idx === 0) ? "done" : ""}><i>{idx + 1}</i><span>{s}</span></div>)}</div>
    <div className="workspace-grid">
      <aside className="control-panel"><div className="panel-title"><span>CONTROL RUN</span><Tag tone={state === "ready" ? "slate" : "green"}>{state === "ready" ? "Not run" : "Completed"}</Tag></div>
        {[['Payload schema', 'Valid · 12/12 fields'], ['Dependency status', incident.id === 'HVB-2841' ? '1 partial dependency' : 'No failed dependencies'], ['Population control', incident.id === 'HVB-2841' ? '184 records missing' : 'Population complete'], ['Materiality', incident.severity === 'Medium' ? 'Review threshold' : 'Escalation threshold'], ['Retrieval trust', `${incident.evidence.filter(e => e.kind === 'Runbook' || e.kind === 'History').length} local documents`]].map(([a,b], idx) => <div className="control-row" key={a}><i className={state === "ready" ? "pending-dot" : idx === 1 && incident.id === 'HVB-2841' ? "warn-dot" : "ok-dot"}></i><div><span>{a}</span><strong>{state === "ready" ? "Pending" : b}</strong></div></div>)}
        <div className="boundary-note"><span>PRODUCTION BOUNDARY</span><p>No tool in this workbench can alter trades, market data, jobs, or report configuration.</p></div>
      </aside>
      <section className="main-panel">
        <div className="tabs">{(["evidence", "recommendation", "approval", "audit"] as const).map(t => <button key={t} className={tab === t ? "active" : ""} onClick={() => setTab(t)}>{t}{t === "evidence" && <b>{incident.evidence.length}</b>}</button>)}</div>
        {tab === "evidence" && <div className="evidence-list">{incident.evidence.map(e => <article key={e.id}><div className="evidence-icon">{e.kind.slice(0,1)}</div><div><div className="evidence-meta"><Tag tone={e.signal === "contradicts" ? "red" : e.signal === "supports" ? "green" : "slate"}>{e.signal}</Tag><span>{e.id} · {e.kind}</span></div><h3>{e.title}</h3><p>{e.detail}</p><small>Source: {e.source}</small></div><button aria-label={`Open ${e.id}`}>↗</button></article>)}</div>}
        {tab === "recommendation" && state === "ready" && <Empty title="Investigation not run" text="Run the controlled workflow to generate a cited recommendation." />}
        {tab === "recommendation" && state !== "ready" && <div className="recommendation"><div className="rec-head"><div><span>STRUCTURED RECOMMENDATION · MOCK PROVIDER</span><h2>{failClosed ? "Root cause not confirmed" : incident.rootCause}</h2></div><div className={`confidence ${failClosed ? "low" : ""}`}><strong>{incident.confidence}%</strong><span>confidence</span></div></div><div className="claim"><span>ASSESSMENT</span><p>{failClosed ? "Available evidence does not support a safe root-cause confirmation." : `The strongest supported explanation is ${incident.rootCause.toLowerCase()}.`} {incident.evidence.slice(0,2).map(e => <button key={e.id} onClick={() => setTab("evidence")}>[{e.id}]</button>)}</p></div><div className="claim"><span>RECOMMENDED NEXT ACTION</span><p>{incident.action} {incident.evidence.filter(e => e.kind === "Runbook").map(e => <button key={e.id} onClick={() => setTab("evidence")}>[{e.id}]</button>)}</p></div><div className="guardrail"><strong>Guardrail applied</strong><p>{incident.guardrail}</p></div><button className="primary" onClick={() => setTab("approval")}>{failClosed ? "Review escalation" : "Review for approval"}</button></div>}
        {tab === "approval" && state === "ready" && <Empty title="No recommendation awaiting approval" text="Complete an investigation first." />}
        {tab === "approval" && state !== "ready" && <div className="approval"><div className="approval-banner"><i>!</i><div><strong>Human decision required</strong><p>The recommendation has no operational effect until an authorised analyst records a decision.</p></div></div><dl><div><dt>Proposed action</dt><dd>{incident.action}</dd></div><div><dt>Escalation path</dt><dd>{incident.escalation}</dd></div><div><dt>Evidence available</dt><dd>{incident.evidence.map(e => e.id).join(", ")}</dd></div><div><dt>Policy result</dt><dd>{failClosed ? "Fail closed · escalation only" : "Approval permitted · no automatic execution"}</dd></div></dl>{state === "complete" ? <div className="decision-actions"><button className="primary" onClick={() => decide("approved")}>Accept recommendation</button><button className="secondary danger" onClick={() => decide("rejected")}>Reject</button></div> : <div className={`decision-record ${state}`}><strong>Recommendation {state}</strong><span>Recorded by Sam Lee · Support Analyst</span></div>}</div>}
        {tab === "audit" && <div className="audit"><div className="audit-head"><h3>Immutable activity record</h3><Tag tone="green">No secrets logged</Tag></div>{audit.length ? audit.map((a, i) => <div key={a}><span>{String(i + 1).padStart(2, "0")}</span><p>{a}</p><code>sha:{(81473 + i * 613).toString(16)}</code></div>) : <Empty title="No activity yet" text="Workflow events appear here after an investigation runs." />}</div>}
      </section>
    </div>
  </>;
}

function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><i>◇</i><h3>{title}</h3><p>{text}</p></div>; }

function Queue({ open }: { open: (i: Incident) => void }) { return <><Header eyebrow="Stage 3 · Deploy" title="Incident queue" text="A controlled daily view across risk, finance, operations, and regulatory reporting." right={<button className="secondary">Export queue</button>} /><div className="metric-grid"><Metric label="Open incidents" value="14" note="3 above baseline" /><Metric label="Critical" value="1" note="human escalation active" tone="redline" /><Metric label="Median triage" value="18m" note="simulated · down 44%" /><Metric label="Knowledge reuse" value="61%" note="simulated this month" /></div><section className="table-card"><div className="table-toolbar"><strong>Active exceptions</strong><div><Tag>All desks</Tag><Tag>All severity</Tag></div></div><table><thead><tr><th>Incident</th><th>Report / area</th><th>Severity</th><th>Status</th><th>Owner</th><th>Age</th><th></th></tr></thead><tbody>{incidents.map(i => <tr key={i.id}><td><button className="text-button" onClick={() => open(i)}><strong>{i.id}</strong><span>{i.title}</span></button></td><td><strong>{i.report}</strong><span>{i.area}</span></td><td><Tag tone={i.severity === "Critical" ? "red" : i.severity === "High" ? "amber" : "blue"}>{i.severity}</Tag></td><td>{i.status}</td><td>{i.owner}</td><td>{i.age}</td><td><button className="arrow" onClick={() => open(i)}>→</button></td></tr>)}</tbody></table></section></>; }

function Discover() { return <><Header eyebrow="Stage 1 · Discover" title="How reporting actually works" text="The engagement begins with the operating process, incentives, handoffs, and conflicting stakeholder accounts." /><div className="section-label"><span>CURRENT-STATE WORKFLOW MAP</span><small>Median daily manual effort shown per stage</small></div><div className="workflow-map">{workflow.map(([n,name,team,out,det,judge,time]) => <article key={n}><div className="flow-num">{n}</div><div><h3>{name}</h3><span>{team}</span></div><dl><dt>Output</dt><dd>{out}</dd><dt>Deterministic</dt><dd>{det}</dd><dt>Judgment point</dt><dd>{judge}</dd></dl><strong>{time}</strong></article>)}</div><div className="section-label interviews-title"><span>STAKEHOLDER INTERVIEW FINDINGS</span><small>Conflicts are signals to investigate—not average away</small></div><div className="interview-grid">{interviews.map(([name,role,quote,conflict]) => <article key={name}><div className="avatar">{name.split(" ").map(s => s[0]).join("")}</div><div><h3>{name}</h3><span>{role}</span><blockquote>“{quote}”</blockquote><p><b>Conflict:</b> {conflict}</p></div></article>)}</div></>; }

function Diagnose() { return <><Header eyebrow="Stage 2 · Diagnose" title="AI opportunity matrix" text="Automation choices are based on workflow characteristics, not the desire to place a model everywhere." /><div className="matrix-layout"><section className="opportunity-chart"><div className="chart-axis y">Business value →</div><div className="quadrant q1"><span>Assist with controls</span></div><div className="quadrant q2"><span>Prioritise</span></div><div className="quadrant q3"><span>Defer</span></div><div className="quadrant q4"><span>Deterministic first</span></div>{opportunities.map((o,i) => <button className={`plot p${i+1}`} key={o[0]} title={o[0]}>{i+1}</button>)}<div className="chart-axis x">Implementation readiness →</div></section><section className="decision-legend"><h3>Decision boundaries</h3>{opportunities.map((o,i) => <div key={o[0]}><i>{i+1}</i><div><strong>{o[0]}</strong><Tag tone={String(o[1]).includes("AI") ? "violet" : String(o[1]).includes("Deterministic") ? "green" : String(o[1]).includes("Human") ? "amber" : "slate"}>{o[1]}</Tag><p>{o[3]}</p></div><b>{o[2]}</b></div>)}</section></div></>; }

function Evaluate() { return <><Header eyebrow="Stage 4 · Evaluate" title="Evidence before confidence" text="A versioned synthetic benchmark tests quality, safety, escalation judgment, and operational value." right={<button className="primary">Run 30-case suite</button>} /><div className="eval-banner"><div><span>LATEST RUN · MOCK-1.2 · 04 AUG 2026 09:04</span><strong>30 / 30 cases completed</strong></div><Tag tone="green">All safety gates passed</Tag></div><div className="eval-grid">{evaluationMetrics.map(([label,value,note,type]) => <Metric key={label} label={label} value={value} note={note} tone={type === "safe" ? "greenline" : ""} />)}</div><div className="eval-bottom"><section className="bar-card"><h3>Performance by incident class</h3>{[['Stale market data',94],['Failed dependency',97],['Missing population',93],['Mapping error',85],['Duplicate trade',88],['Valuation movement',90],['Currency conversion',87],['Incomplete file',96]].map(([n,v]) => <div className="bar" key={n}><span>{n}</span><i><b style={{width:`${v}%`}} /></i><strong>{v}%</strong></div>)}</section><section className="failure-card"><h3>Fail-closed coverage</h3>{[['Insufficient evidence','6/6'],['Conflicting documents','4/4'],['Critical incidents','3/3'],['Prohibited mutation','5/5'],['Invalid model schema','4/4']].map(([a,b]) => <div key={a}><span>✓</span><p>{a}</p><strong>{b}</strong></div>)}<small>Simulated benchmark results; not production performance claims.</small></section></div></>; }

function Observe() { const spans = ["incident.validate", "evidence.reconcile", "dependency.inspect", "retrieval.search", "model.synthesize", "schema.validate", "guardrail.decide", "approval.request"]; return <><Header eyebrow="Observability" title="Trace HVB-2847 · run 01K2" text="A safe, redacted view of every deterministic, retrieval, model, validation, and policy decision." /><div className="trace-summary"><Metric label="Disposition" value="Approval required" note="no action executed" /><Metric label="Latency" value="1.84s" note="simulated total" /><Metric label="Tokens" value="1,246" note="mock metadata" /><Metric label="Est. cost" value="$0.006" note="projected AUD" /></div><section className="trace-card"><div className="trace-head"><span>SPAN</span><span>TYPE</span><span>TIMELINE</span><span>DURATION</span><span>RESULT</span></div>{spans.map((s,i) => <div className="trace-row" key={s}><code>{s}</code><Tag tone={i < 3 || i > 4 ? "green" : i === 4 ? "violet" : "blue"}>{i === 3 ? "Retrieval" : i === 4 ? "Model" : "Deterministic"}</Tag><i><b style={{marginLeft:`${i*8}%`,width:`${Math.max(8,31-i*2)}%`}} /></i><span>{[22,318,84,196,784,18,9,3][i]}ms</span><strong>✓ Pass</strong></div>)}</section><div className="safe-prompt"><span>SAFE DEVELOPER VIEW</span><p>Prompt templates expose task instructions and schemas. Secrets, raw private notes, and sensitive identifiers are redacted.</p><button className="secondary">Inspect template</button></div></>; }

function Govern() { return <><Header eyebrow="Security & governance" title="Guardrails are part of the product" text="Policies constrain inputs, evidence, model outputs, permissions, actions, cost, and retention." /><div className="govern-grid">{[["Access control","Role-based permissions","Support analysts cannot edit policy or evaluation records.","Enforced"],["Output safety","Strict schema validation","Invalid fields and uncited claims stop the workflow.","Enforced"],["Agent limits","Maximum 12 steps","Timeout 30s · retry limit 2 · idempotency key required.","Enforced"],["Data boundary","No production mutation","Trade, market-data, and configuration writes do not exist.","Hard boundary"],["Retrieval trust","Injection-resistant ingestion","Documents are treated as evidence, not executable instructions.","Enforced"],["Privacy","Synthetic data + redaction","Secrets and sensitive values are removed before logs or providers.","Enforced"],["Retention","30-day trace default","Configurable by environment; approvals retained for audit.","Configured"],["Cost control","Per-run budget","Requests stop before provider and step budgets are exceeded.","Enforced"]].map(([a,b,c,d]) => <article key={a}><div><span>{a}</span><Tag tone="green">{d}</Tag></div><h3>{b}</h3><p>{c}</p></article>)}</div><section className="threat-table"><h3>Threat model snapshot</h3>{[["Malicious runbook content","High","Trust metadata, instruction stripping, citations"],["Hallucinated root cause","High","Closed evidence set, schema validation, confidence gate"],["Unauthorised operational action","Critical","RBAC + absent mutation tools + explicit approval"],["Poisoned incident history","High","Source provenance, recency and conflict checks"],["Model provider outage","Medium","Mock/local fallback and deterministic evidence remains available"],["Incomplete audit trail","High","Append-only events and idempotent execution"]].map(r => <div key={r[0]}><strong>{r[0]}</strong><Tag tone={r[1] === "Critical" ? "red" : r[1] === "High" ? "amber" : "blue"}>{r[1]}</Tag><span>{r[2]}</span></div>)}</section></>; }

function Value() { const [incidentsPerMonth, setIncidentsPerMonth] = useState(180); const [minutes, setMinutes] = useState(74); const hours = Math.round(incidentsPerMonth * minutes * 12 / 60); const benefit = Math.round(hours * 92 * .65); return <><Header eyebrow="Stage 5 · Prove value" title="Conservative value case" text="Measured, simulated, assumed, and projected values stay visibly separate." /><div className="value-grid"><Metric label="Baseline investigation" value="126m" note="simulated process study" /><Metric label="Assisted investigation" value="52m" note="simulated benchmark" /><Metric label="Annual hours released" value={hours.toLocaleString()} note="projection" /><Metric label="Estimated annual benefit" value={`$${(benefit/1000).toFixed(0)}k`} note="projection · AUD" /><Metric label="Operating cost" value="$68k" note="assumption · annual" /><Metric label="Payback" value="8.4 mo" note="projection · range 6–14" /></div><div className="roi-layout"><section className="roi-card"><div><h3>Editable ROI assumptions</h3><Tag tone="amber">Conservative defaults</Tag></div><label>Incidents per month <output>{incidentsPerMonth}</output><input type="range" min="80" max="320" value={incidentsPerMonth} onChange={e => setIncidentsPerMonth(+e.target.value)} /></label><label>Minutes saved per incident <output>{minutes}</output><input type="range" min="20" max="110" value={minutes} onChange={e => setMinutes(+e.target.value)} /></label><label>Loaded analyst cost / hour <output>AUD 92</output><input type="range" min="60" max="140" value="92" readOnly /></label><p>Benefit applies a 65% realisation factor; it does not assume every released hour becomes cash savings.</p></section><section className="waterfall"><h3>Annual value bridge · AUD</h3>{[["Gross capacity", benefit/.65],["Realisation adjustment",-benefit*.22],["Operating cost",-68000],["Risk-adjusted benefit", benefit-68000]].map(([a,b]) => <div key={a}><span>{a}</span><i><b className={Number(b)<0 ? "negative" : ""} style={{width:`${Math.min(100, Math.abs(Number(b))/(benefit/.65)*100)}%`}} /></i><strong>{Number(b)<0?"−":""}${Math.abs(Number(b)/1000).toFixed(0)}k</strong></div>)}</section></div><div className="legend-row"><Tag tone="blue">Measured: none yet</Tag><Tag tone="violet">Simulated: workflow benchmark</Tag><Tag tone="amber">Assumed: volume, cost, realisation</Tag><Tag tone="green">Projected: benefits and payback</Tag></div></>; }

function Report() { return <><Header eyebrow="Engagement overview" title="HarbourView reporting resilience" text="A six-week FDE engagement turning fragmented exception handling into a controlled, evidence-backed workflow." right={<button className="secondary">Download brief</button>} /><div className="report-hero"><div><span>EXECUTIVE FINDING</span><h2>The constraint is not access to more AI. It is the cost of assembling trustworthy evidence across handoffs.</h2><p>The proposed workbench shortens evidence gathering and communication while preserving accountable operational decisions.</p></div><div className="phase-list">{[["01","Discover","Map the real process and reconcile stakeholder conflict"],["02","Diagnose","Prioritise deterministic controls and bounded AI assistance"],["03","Deploy","Pilot five report exception classes in shadow mode"],["04","Evaluate","Gate release on quality, safety, and escalation metrics"],["05","Adopt","Train analysts, measure acceptance, expand by evidence"]].map(x => <div key={x[0]}><i>{x[0]}</i><div><strong>{x[1]}</strong><span>{x[2]}</span></div></div>)}</div></div><div className="report-columns"><section><span>WHAT CHANGES</span><h3>From manual search to a governed case file</h3><ul><li>Control results arrive before model synthesis</li><li>Every proposed cause is linked to evidence</li><li>Contradictions reduce confidence visibly</li><li>Approvals and rejections become evaluation data</li></ul></section><section><span>WHAT DOES NOT CHANGE</span><h3>Humans remain accountable</h3><ul><li>Production reruns require authorised approval</li><li>Trade and market-data repair stays outside the agent</li><li>Critical incidents follow the incident-command process</li><li>Business owners accept materiality and release decisions</li></ul></section><section><span>ADOPTION STRATEGY</span><h3>Shadow, assist, then scale</h3><ul><li>Weeks 1–2: observe and benchmark only</li><li>Weeks 3–4: analyst-assist with full review</li><li>Weeks 5–6: controlled pilot by incident class</li><li>Scale only after safety gates stay green</li></ul></section></div></>; }

function Architecture() { return <><Header eyebrow="Architecture" title="Explicit system boundaries" text="The workflow is inspectable end to end; no unconstrained agent framework hides operational decisions." /><div className="arch"><div className="arch-personas"><span>USERS</span>{["Support Analyst","FDE / Engineer","Executive Sponsor"].map(x => <b key={x}>{x}</b>)}</div><div className="arch-arrow">↓</div><div className="arch-layer"><span>WORKBENCH</span>{["Incident experience","Opportunity & evaluation","Governance & value"].map(x => <b key={x}>{x}</b>)}</div><div className="arch-arrow">↓</div><div className="arch-split"><section><span>DETERMINISTIC SERVICES</span>{["Validation","Reconciliation","Thresholds","Permissions","State machine"].map(x => <b key={x}>{x}</b>)}</section><section className="retrieval"><span>RETRIEVAL</span>{["Runbooks","Incident history","Change records"].map(x => <b key={x}>{x}</b>)}</section><section className="ai"><span>BOUNDED AI</span>{["Evidence synthesis","Cause ranking","Summary drafting"].map(x => <b key={x}>{x}</b>)}</section></div><div className="arch-arrow">↓</div><div className="arch-layer dark"><span>CONTROL PLANE</span>{["Approval gates","Audit events","Traces","Evaluation harness"].map(x => <b key={x}>{x}</b>)}</div><div className="no-write">⊘ No production write path exists in the demonstration</div></div></>; }

function Demo({ launch }: { launch: (i: Incident) => void }) { return <><Header eyebrow="Portfolio demo" title="Five evidence-backed scenarios" text="Each scenario demonstrates a different deployment judgment, including when the system should refuse to conclude." /><div className="scenario-grid">{incidents.map((i,idx) => <article key={i.id}><div className="scenario-top"><i>0{idx+1}</i><Tag tone={idx === 4 ? "red" : idx === 3 ? "green" : "blue"}>{idx === 4 ? "Fail closed" : idx === 3 ? "No remediation" : "Human approval"}</Tag></div><h2>{i.title}</h2><p>{i.description}</p><div><span>Key judgment</span><strong>{i.guardrail}</strong></div><button className="primary" onClick={() => launch(i)}>Launch scenario →</button></article>)}</div><div className="demo-script"><span>7–10 MINUTE STORY</span><p><b>1.</b> Real operating pattern &nbsp;→&nbsp; <b>2.</b> Discover the workflow &nbsp;→&nbsp; <b>3.</b> Draw AI boundaries &nbsp;→&nbsp; <b>4.</b> Investigate with evidence &nbsp;→&nbsp; <b>5.</b> Fail safely &nbsp;→&nbsp; <b>6.</b> Evaluate &nbsp;→&nbsp; <b>7.</b> Prove value</p></div></>; }

export default function Home() {
  const [view, setView] = useState<View>("investigate"); const [incident, setIncident] = useState(incidents[0]); const [persona, setPersona] = useState("Support Analyst"); const [state, setState] = useState<InvestigationState>("ready"); const [audit, setAudit] = useState<string[]>([]);
  const grouped = useMemo(() => nav.reduce<Record<string, typeof nav>>((a,n) => ((a[n.kicker] ||= []).push(n), a), {}), []);
  const open = (i: Incident) => { setIncident(i); setState("ready"); setAudit([]); setView("investigate"); };
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div>HV</div><span><strong>Murex FDE</strong><small>WORKBENCH</small></span></div><div className="bank"><span>FICTIONAL CLIENT</span><strong>HarbourView Bank</strong><small>Capital Markets · Sydney</small></div><nav>{Object.entries(grouped).map(([group,items]) => <div key={group}><span>{group}</span>{items.map(n => <button key={n.view} className={view === n.view ? "active" : ""} onClick={() => setView(n.view)}><i>{({investigate:"⌁",queue:"≡",discover:"⌘",diagnose:"◫",evaluate:"✓",observe:"⌁",govern:"◇",value:"↗",report:"▤",architecture:"⌗",demo:"▷"} as Record<View,string>)[n.view]}</i>{n.label}</button>)}</div>)}</nav><div className="sidebar-foot"><span>DEMO ENVIRONMENT</span><div><i></i> Mock model · Local data</div><small>No production connectivity</small></div></aside><main><div className="topbar"><div className="breadcrumb"><span>HarbourView Bank</span><b>/</b><strong>{nav.find(n => n.view === view)?.label}</strong></div><div className="top-actions"><button aria-label="Notifications">◌<i></i></button><select aria-label="Current persona" value={persona} onChange={e => setPersona(e.target.value)}><option>Support Analyst</option><option>FDE / Implementation Engineer</option><option>Executive / Programme Sponsor</option></select><div className="user">SL</div></div></div><div className="page">
    {view === "investigate" && <Investigation incident={incident} setIncident={setIncident} state={state} setState={setState} audit={audit} setAudit={setAudit} />}
    {view === "queue" && <Queue open={open} />}{view === "discover" && <Discover />}{view === "diagnose" && <Diagnose />}{view === "evaluate" && <Evaluate />}{view === "observe" && <Observe />}{view === "govern" && <Govern />}{view === "value" && <Value />}{view === "report" && <Report />}{view === "architecture" && <Architecture />}{view === "demo" && <Demo launch={open} />}
  </div><footer><span>Independent educational simulation · All data and workflows are fictional</span><span>Murex is a trademark of its respective owner · Not affiliated with or endorsed by Murex</span></footer></main></div>;
}
