"use client";

import { useEffect, useMemo, useState } from "react";
import type { InvestigationRun } from "../src/domain/models";
import { incidents, interviews, opportunities, workflow, type Incident } from "./data";
import { ExecutableEvaluation } from "./components/ExecutableEvaluation";
import { ExecutableInvestigation } from "./components/ExecutableInvestigation";
import { ExecutableObservability } from "./components/ExecutableObservability";

type View = "investigate" | "queue" | "discover" | "diagnose" | "evaluate" | "observe" | "govern" | "value" | "report" | "architecture" | "demo";
type InvestigationState = "ready" | "complete" | "approved" | "rejected";

const nav: { label: string; view: View; kicker: string }[] = [
  { label: "Investigation workspace", view: "investigate", kicker: "Deploy" },
  { label: "Incident queue", view: "queue", kicker: "Deploy" },
  { label: "Workflow & interviews", view: "discover", kicker: "Discover" },
  { label: "Opportunity matrix", view: "diagnose", kicker: "Diagnose" },
  { label: "Evaluation dashboard", view: "evaluate", kicker: "Evaluate" },
  { label: "Observability & traces", view: "observe", kicker: "Evaluate" },
  { label: "Governance controls", view: "govern", kicker: "Control" },
  { label: "ROI & value", view: "value", kicker: "Prove value" },
  { label: "FDE engagement report", view: "report", kicker: "Engagement" },
  { label: "System boundaries", view: "architecture", kicker: "Architecture" },
  { label: "Demo launcher", view: "demo", kicker: "Portfolio" },
];

function Tag({ children, tone = "slate" }: { children: React.ReactNode; tone?: string }) {
  return <span className={`tag tag-${tone}`}>{children}</span>;
}

function Header({ eyebrow, title, text, right }: { eyebrow: string; title: string; text: string; right?: React.ReactNode }) {
  return <header className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div>{right}</header>;
}

function Metric({ label, value, note, tone }: { label: string; value: string; note: string; tone?: string }) {
  return <div className={`metric ${tone || ""}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>;
}

function Investigation({ incident, setIncident, state, setState, audit, setAudit }: { incident: Incident; setIncident: (i: Incident) => void; state: InvestigationState; setState: (s: InvestigationState) => void; audit: string[]; setAudit: (a: string[]) => void }) {
  const [tab, setTab] = useState<"evidence" | "recommendation" | "approval" | "audit">("evidence");
  const run = () => { setState("complete"); setTab("recommendation"); setAudit(["09:14:03 · Payload validated · schema v1.2", "09:14:04 · Deterministic controls completed · 3 checks", "09:14:04 · Local retrieval completed · trusted documents only", "09:14:05 · Recommendation validated · 4 citations", "09:14:05 · Approval gate opened · no action executed"]); };
  const decide = (decision: "approved" | "rejected") => { setState(decision); setTab("audit"); setAudit([...audit, `09:16:22 · Recommendation ${decision} · analyst.s.lee · demo session`]); };
  const failClosed = incident.confidence < 70 || incident.severity === "Critical";
  return <>
    <Header eyebrow="Stage 3 · Deploy" title="Exception investigation" text="Deterministic controls first. AI synthesis second. An accountable human decides." right={<div className="head-actions"><select aria-label="Select incident" value={incident.id} onChange={e => { setIncident(incidents.find(i => i.id === e.target.value)!); setState("ready"); setAudit([]); }} className="select">{incidents.map(i => <option key={i.id}>{i.id}</option>)}</select><button className="primary" onClick={run}>{state === "ready" ? "Run controlled investigation" : "Run again"}</button></div>} />
    <div className="context-strip"><div><span>INCIDENT</span><strong>{incident.id}</strong></div><div><span>REPORT</span><strong>{incident.report}</strong></div><div><span>BUSINESS DATE</span><strong>{incident.businessDate}</strong></div><div><span>OWNER</span><strong>{incident.owner}</strong></div><div><span>SEVERITY</span><Tag tone={incident.severity === "Critical" ? "red" : incident.severity === "High" ? "amber" : "blue"}>{incident.severity}</Tag></div></div>
    <section className="incident-summary"><div><div className="row-title"><h2>{incident.title}</h2><Tag tone="blue">{incident.status}</Tag></div><p>{incident.description}</p></div><div className="impact"><span>Potential impact</span><strong>{incident.impact}</strong></div></section>
    <div className="stepper" aria-label="Investigation stages">{["Validate", "Gather", "Retrieve", "Synthesize", "Approve", "Record"].map((s, idx) => <div key={s} className={(state !== "ready" || idx === 0) ? "done" : ""}><i>{idx + 1}</i><span>{s}</span></div>)}</div>
    <div className="workspace-grid">
      <aside className="control-panel"><div className="panel-title"><span>CONTROL RUN</span><Tag tone={state === "ready" ? "slate" : "green"}>{state === "ready" ? "Not run" : "Completed"}</Tag></div>
        {[['Payload schema', 'Valid · 12/12 fields'], ['Dependency status', incident.id === 'HVB-2841' ? '1 partial dependency' : 'No failed dependencies'], ['Population control', incident.id === 'HVB-2841' ? '184 records missing' : 'Population complete'], ['Materiality', incident.severity === 'Medium' ? 'Review threshold' : 'Escalation threshold'], ['Retrieval trust', `${incident.evidence.filter(e => e.kind === 'Runbook' || e.kind === 'History').length} local documents`]].map(([a,b], idx) => <div className="control-row" key={a}><i className={state === "ready" ? "pending-dot" : idx === 1 && incident.id === 'HVB-2841' ? "warn-dot" : "ok-dot"}></i><div><span>{a}</span><strong>{state === "ready" ? "Pending" : b}</strong></div></div>)}
        <div className="boundary-note"><span>PRODUCTION BOUNDARY</span><p>No tool in this workbench can alter trades, market data, jobs, or report configuration.</p></div>
      </aside>
      <section className="main-panel">
        <div className="tabs">{(["evidence", "recommendation", "approval", "audit"] as const).map(t => <button key={t} className={tab === t ? "active" : ""} onClick={() => setTab(t)}>{t}{t === "evidence" && <b>{incident.evidence.length}</b>}</button>)}</div>
        {tab === "evidence" && <div className="evidence-list">{incident.evidence.map(e => <article key={e.id}><div className="evidence-icon">{e.kind.slice(0,1)}</div><div><div className="evidence-meta"><Tag tone={e.signal === "contradicts" ? "red" : e.signal === "supports" ? "green" : "slate"}>{e.signal}</Tag><span>{e.id} · {e.kind}</span></div><h3>{e.title}</h3><p>{e.detail}</p><small>Source: {e.source}</small></div><button aria-label={`Open ${e.id}`}>↗</button></article>)}</div>}
        {tab === "recommendation" && state === "ready" && <Empty title="Investigation not run" text="Run the controlled workflow to generate a cited recommendation." />}
        {tab === "recommendation" && state !== "ready" && <div className="recommendation"><div className="rec-head"><div><span>STRUCTURED RECOMMENDATION · MOCK PROVIDER</span><h2>{failClosed ? "Root cause not confirmed" : incident.rootCause}</h2></div><div className={`confidence ${failClosed ? "low" : ""}`}><strong>{incident.confidence}%</strong><span>confidence</span></div></div><div className="claim"><span>ASSESSMENT</span><p>{failClosed ? "Available evidence does not support a safe root-cause confirmation." : `The strongest supported explanation is ${incident.rootCause.toLowerCase()}.`} {incident.evidence.slice(0,2).map(e => <button key={e.id} onClick={() => setTab("evidence")}>[{e.id}]</button>)}</p></div><div className="claim"><span>RECOMMENDED NEXT ACTION</span><p>{incident.action} {incident.evidence.filter(e => e.kind === "Runbook").map(e => <button key={e.id} onClick={() => setTab("evidence")}>[{e.id}]</button>)}</p></div><div className="guardrail"><strong>Guardrail applied</strong><p>{incident.guardrail}</p></div><button className="primary" onClick={() => setTab("approval")}>{failClosed ? "Review escalation" : "Review for approval"}</button></div>}
        {tab === "approval" && state === "ready" && <Empty title="No recommendation awaiting approval" text="Complete an investigation first." />}
        {tab === "approval" && state !== "ready" && <div className="approval"><div className="approval-banner"><i>!</i><div><strong>Human decision required</strong><p>The recommendation has no operational effect until an authorised analyst records a decision.</p></div></div><dl><div><dt>Proposed action</dt><dd>{incident.action}</dd></div><div><dt>Escalation path</dt><dd>{incident.escalation}</dd></div><div><dt>Evidence available</dt><dd>{incident.evidence.map(e => e.id).join(", ")}</dd></div><div><dt>Policy result</dt><dd>{failClosed ? "Fail closed · escalation only" : "Approval permitted · no automatic execution"}</dd></div></dl>{state === "complete" ? <div className="decision-actions"><button className="primary" onClick={() => decide("approved")}>Accept recommendation</button><button className="secondary danger" onClick={() => decide("rejected")}>Reject</button></div> : <div className={`decision-record ${state}`}><strong>Recommendation {state}</strong><span>Recorded by Sam Lee · Support Analyst</span></div>}</div>}
        {tab === "audit" && <div className="audit"><div className="audit-head"><h3>Immutable activity record</h3><Tag tone="green">No secrets logged</Tag></div>{audit.length ? audit.map((a, i) => <div key={a}><span>{String(i + 1).padStart(2, "0")}</span><p>{a}</p><code>sha:{(81473 + i * 613).toString(16)}</code></div>) : <Empty title="No activity yet" text="Workflow events appear here after an investigation runs." />}</div>}
      </section>
    </div>
  </>;
}

function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><i>◇</i><h3>{title}</h3><p>{text}</p></div>; }

const executableIds = new Set(["HVB-2847", "HVB-2829", "HVB-2822"]);
function useExecutableRuns() { const [runs, setRuns] = useState<Record<string, InvestigationRun | null>>({}); useEffect(() => { Promise.all([...executableIds].map(async incidentId => { const response = await fetch(`/api/investigations?incidentId=${incidentId}`); const data = response.ok ? await response.json() as { run: InvestigationRun | null } : { run: null }; return [incidentId, data.run] as const; })).then(entries => setRuns(Object.fromEntries(entries))).catch(() => undefined); }, []); return runs; }
function runState(id: string, run: InvestigationRun | null | undefined) { if (!executableIds.has(id)) return { label: "Preview", tone: "slate" }; if (!run) return { label: "Executable · not run", tone: "blue" }; if (run.approval) return { label: run.approval.decision === "approved" ? "Approved" : "Rejected", tone: run.approval.decision === "approved" ? "green" : "red" }; if (run.status === "failed_closed") return { label: "Failed closed · awaiting disposition", tone: "red" }; return { label: "Awaiting decision", tone: "amber" }; }
function Queue({ open }: { open: (i: Incident) => void }) { const runs = useExecutableRuns(); const awaiting = Object.values(runs).filter(run => run && !run.approval).length; return <><Header eyebrow="Stage 3 · Deploy" title="Incident queue" text="Three executable cases and two clearly labelled previews across risk, finance, operations, and regulatory reporting." right={<button className="secondary">Export queue</button>} /><div className="metric-grid"><Metric label="Executable cases" value="3" note="persisted shared workflow" /><Metric label="Critical" value="1" note="fail-closed escalation" tone="redline" /><Metric label="Awaiting decision" value={String(awaiting)} note="actual persisted state" /><Metric label="Preview only" value="2" note="not measured" /></div><section className="table-card"><div className="table-toolbar"><strong>Active exceptions</strong><div><Tag>All desks</Tag><Tag>All severity</Tag></div></div><table><thead><tr><th>Incident</th><th>Report / area</th><th>Severity</th><th>Execution</th><th>Owner</th><th>Age</th><th></th></tr></thead><tbody>{incidents.map(i => { const state = runState(i.id, runs[i.id]); return <tr key={i.id}><td><button className="text-button" onClick={() => open(i)}><strong>{i.id}</strong><span>{i.title}</span></button></td><td><strong>{i.report}</strong><span>{i.area}</span></td><td><Tag tone={i.severity === "Critical" ? "red" : i.severity === "High" ? "amber" : "blue"}>{i.severity}</Tag></td><td><Tag tone={state.tone}>{state.label}</Tag></td><td>{i.owner}</td><td>{i.age}</td><td><button className="arrow" onClick={() => open(i)}>→</button></td></tr>; })}</tbody></table></section></>; }

function Discover() { return <><Header eyebrow="Stage 1 · Discover" title="How reporting actually works" text="The engagement begins with the operating process, incentives, handoffs, and conflicting stakeholder accounts." /><div className="section-label"><span>CURRENT-STATE WORKFLOW MAP</span><small>Median daily manual effort shown per stage</small></div><div className="workflow-map">{workflow.map(([n,name,team,out,det,judge,time]) => <article key={n}><div className="flow-num">{n}</div><div><h3>{name}</h3><span>{team}</span></div><dl><dt>Output</dt><dd>{out}</dd><dt>Deterministic</dt><dd>{det}</dd><dt>Judgment point</dt><dd>{judge}</dd></dl><strong>{time}</strong></article>)}</div><div className="section-label interviews-title"><span>STAKEHOLDER INTERVIEW FINDINGS</span><small>Conflicts are signals to investigate—not average away</small></div><div className="interview-grid">{interviews.map(([name,role,quote,conflict]) => <article key={name}><div className="avatar">{name.split(" ").map(s => s[0]).join("")}</div><div><h3>{name}</h3><span>{role}</span><blockquote>“{quote}”</blockquote><p><b>Conflict:</b> {conflict}</p></div></article>)}</div></>; }

function Diagnose() { return <><Header eyebrow="Stage 2 · Diagnose" title="AI opportunity matrix" text="Automation choices are based on workflow characteristics, not the desire to place a model everywhere." /><div className="matrix-layout"><section className="opportunity-chart"><div className="chart-axis y">Business value →</div><div className="quadrant q1"><span>Assist with controls</span></div><div className="quadrant q2"><span>Prioritise</span></div><div className="quadrant q3"><span>Defer</span></div><div className="quadrant q4"><span>Deterministic first</span></div>{opportunities.map((o,i) => <button className={`plot p${i+1}`} key={String(o[0])} title={String(o[0])}>{i+1}</button>)}<div className="chart-axis x">Implementation readiness →</div></section><section className="decision-legend"><h3>Decision boundaries</h3>{opportunities.map((o,i) => <div key={String(o[0])}><i>{i+1}</i><div><strong>{o[0]}</strong><Tag tone={String(o[1]).includes("AI") ? "violet" : String(o[1]).includes("Deterministic") ? "green" : String(o[1]).includes("Human") ? "amber" : "slate"}>{o[1]}</Tag><p>{o[3]}</p></div><b>{o[2]}</b></div>)}</section></div></>; }

function Govern() { return <><Header eyebrow="Security & governance" title="Guardrails are part of the product" text="Policies constrain inputs, evidence, model outputs, permissions, actions, cost, and retention." /><div className="govern-grid">{[["Access control","Role-based permissions","Support analysts cannot edit policy or evaluation records.","Enforced"],["Output safety","Strict schema validation","Invalid fields and uncited claims stop the workflow.","Enforced"],["Agent limits","Maximum 12 steps","Timeout 30s · retry limit 2 · idempotency key required.","Enforced"],["Data boundary","No production mutation","Trade, market-data, and configuration writes do not exist.","Hard boundary"],["Retrieval trust","Injection-resistant ingestion","Documents are treated as evidence, not executable instructions.","Enforced"],["Privacy","Synthetic data + redaction","Secrets and sensitive values are removed before logs or providers.","Enforced"],["Retention","30-day trace default","Configurable by environment; approvals retained for audit.","Configured"],["Cost control","Per-run budget","Requests stop before provider and step budgets are exceeded.","Enforced"]].map(([a,b,c,d]) => <article key={a}><div><span>{a}</span><Tag tone="green">{d}</Tag></div><h3>{b}</h3><p>{c}</p></article>)}</div><section className="threat-table"><h3>Threat model snapshot</h3>{[["Malicious runbook content","High","Trust metadata, instruction stripping, citations"],["Hallucinated root cause","High","Closed evidence set, schema validation, confidence gate"],["Unauthorised operational action","Critical","RBAC + absent mutation tools + explicit approval"],["Poisoned incident history","High","Source provenance, recency and conflict checks"],["Model provider outage","Medium","Mock/local fallback and deterministic evidence remains available"],["Incomplete audit trail","High","Append-only events and idempotent execution"]].map(r => <div key={r[0]}><strong>{r[0]}</strong><Tag tone={r[1] === "Critical" ? "red" : r[1] === "High" ? "amber" : "blue"}>{r[1]}</Tag><span>{r[2]}</span></div>)}</section></>; }

function Value() { const [incidentsPerMonth, setIncidentsPerMonth] = useState(180); const [minutes, setMinutes] = useState(74); const hours = Math.round(incidentsPerMonth * minutes * 12 / 60); const benefit = Math.round(hours * 92 * .65); return <><Header eyebrow="Stage 5 · Prove value" title="Conservative value case" text="Measured, simulated, assumed, and projected values stay visibly separate." /><div className="value-grid"><Metric label="Baseline investigation" value="126m" note="simulated process study" /><Metric label="Assisted investigation" value="52m" note="simulated benchmark" /><Metric label="Annual hours released" value={hours.toLocaleString()} note="projection" /><Metric label="Estimated annual benefit" value={`$${(benefit/1000).toFixed(0)}k`} note="projection · AUD" /><Metric label="Operating cost" value="$68k" note="assumption · annual" /><Metric label="Payback" value="8.4 mo" note="projection · range 6–14" /></div><div className="roi-layout"><section className="roi-card"><div><h3>Editable ROI assumptions</h3><Tag tone="amber">Conservative defaults</Tag></div><label>Incidents per month <output>{incidentsPerMonth}</output><input type="range" min="80" max="320" value={incidentsPerMonth} onChange={e => setIncidentsPerMonth(+e.target.value)} /></label><label>Minutes saved per incident <output>{minutes}</output><input type="range" min="20" max="110" value={minutes} onChange={e => setMinutes(+e.target.value)} /></label><label>Loaded analyst cost / hour <output>AUD 92</output><input type="range" min="60" max="140" value="92" readOnly /></label><p>Benefit applies a 65% realisation factor; it does not assume every released hour becomes cash savings.</p></section><section className="waterfall"><h3>Annual value bridge · AUD</h3>{[["Gross capacity", benefit/.65],["Realisation adjustment",-benefit*.22],["Operating cost",-68000],["Risk-adjusted benefit", benefit-68000]].map(([a,b]) => <div key={a}><span>{a}</span><i><b className={Number(b)<0 ? "negative" : ""} style={{width:`${Math.min(100, Math.abs(Number(b))/(benefit/.65)*100)}%`}} /></i><strong>{Number(b)<0?"−":""}${Math.abs(Number(b)/1000).toFixed(0)}k</strong></div>)}</section></div><div className="legend-row"><Tag tone="blue">Measured: none yet</Tag><Tag tone="violet">Simulated: workflow benchmark</Tag><Tag tone="amber">Assumed: volume, cost, realisation</Tag><Tag tone="green">Projected: benefits and payback</Tag></div></>; }

function Report() { return <><Header eyebrow="Engagement overview" title="HarbourView reporting resilience" text="A six-week FDE engagement turning fragmented exception handling into a controlled, evidence-backed workflow." right={<button className="secondary">Download brief</button>} /><div className="report-hero"><div><span>EXECUTIVE FINDING</span><h2>The constraint is not access to more AI. It is the cost of assembling trustworthy evidence across handoffs.</h2><p>The proposed workbench shortens evidence gathering and communication while preserving accountable operational decisions.</p></div><div className="phase-list">{[["01","Discover","Map the real process and reconcile stakeholder conflict"],["02","Diagnose","Prioritise deterministic controls and bounded AI assistance"],["03","Deploy","Pilot five report exception classes in shadow mode"],["04","Evaluate","Gate release on quality, safety, and escalation metrics"],["05","Adopt","Train analysts, measure acceptance, expand by evidence"]].map(x => <div key={x[0]}><i>{x[0]}</i><div><strong>{x[1]}</strong><span>{x[2]}</span></div></div>)}</div></div><div className="report-columns"><section><span>WHAT CHANGES</span><h3>From manual search to a governed case file</h3><ul><li>Control results arrive before model synthesis</li><li>Every proposed cause is linked to evidence</li><li>Contradictions reduce confidence visibly</li><li>Approvals and rejections become evaluation data</li></ul></section><section><span>WHAT DOES NOT CHANGE</span><h3>Humans remain accountable</h3><ul><li>Production reruns require authorised approval</li><li>Trade and market-data repair stays outside the agent</li><li>Critical incidents follow the incident-command process</li><li>Business owners accept materiality and release decisions</li></ul></section><section><span>ADOPTION STRATEGY</span><h3>Shadow, assist, then scale</h3><ul><li>Weeks 1–2: observe and benchmark only</li><li>Weeks 3–4: analyst-assist with full review</li><li>Weeks 5–6: controlled pilot by incident class</li><li>Scale only after safety gates stay green</li></ul></section></div></>; }

function Architecture() { return <><Header eyebrow="Architecture" title="Explicit system boundaries" text="The workflow is inspectable end to end; no unconstrained agent framework hides operational decisions." /><div className="arch"><div className="arch-personas"><span>USERS</span>{["Support Analyst","FDE / Engineer","Executive Sponsor"].map(x => <b key={x}>{x}</b>)}</div><div className="arch-arrow">↓</div><div className="arch-layer"><span>WORKBENCH</span>{["Incident experience","Opportunity & evaluation","Governance & value"].map(x => <b key={x}>{x}</b>)}</div><div className="arch-arrow">↓</div><div className="arch-split"><section><span>DETERMINISTIC SERVICES</span>{["Validation","Reconciliation","Thresholds","Permissions","State machine"].map(x => <b key={x}>{x}</b>)}</section><section className="retrieval"><span>RETRIEVAL</span>{["Runbooks","Incident history","Change records"].map(x => <b key={x}>{x}</b>)}</section><section className="ai"><span>BOUNDED AI</span>{["Evidence synthesis","Cause ranking","Summary drafting"].map(x => <b key={x}>{x}</b>)}</section></div><div className="arch-arrow">↓</div><div className="arch-layer dark"><span>CONTROL PLANE</span>{["Approval gates","Audit events","Traces","Evaluation harness"].map(x => <b key={x}>{x}</b>)}</div><div className="no-write">⊘ No production write path exists in the demonstration</div></div></>; }

type DemoTourStep = { eyebrow: string; title: string; body: string; label: string; incidentId?: string; tone: "green" | "amber" | "red" | "blue" };
const demoTourSteps: DemoTourStep[] = [
  { eyebrow: "01 · FRAME THE DEMO", title: "A controlled workflow for high-consequence exceptions", body: "This is a synthetic HarbourView Bank scenario. Deterministic controls establish what is true, bounded AI drafts a cited explanation, and an authorised human owns the disposition.", label: "Set the boundary", tone: "blue" },
  { eyebrow: "02 · FLAGSHIP RECOVERY", title: "HVB-2847 · Diagnose, approve, simulate, validate", body: "The workflow exposes a stale USD/JPY timestamp, quantifies affected exposure, validates a cited recommendation, gates one allow-listed synthetic refresh and risk rerun, then lets deterministic post-action controls—not AI—decide resolution.", label: "Deterministic controls first", incidentId: "HVB-2847", tone: "green" },
  { eyebrow: "03 · EXPLAIN", title: "HVB-2829 · Do not turn a threshold into an error", body: "The synthetic crude move reconciles to sensitivity, carry, and new trades. The bounded recommendation is explanation and Product Control review—not remediation.", label: "Bounded AI, grounded in facts", incidentId: "HVB-2829", tone: "amber" },
  { eyebrow: "04 · CONTROLLED RECOVERY", title: "HVB-2822 · Fail closed, gather evidence, recover safely", body: "The first pass refuses to guess. Additional manifest, transfer, mapping, configuration, and volume evidence establishes upstream non-delivery. A human then approves one scoped synthetic recovery, followed by downstream validation and closure.", label: "Human approval is the gate", incidentId: "HVB-2822", tone: "red" },
  { eyebrow: "05 · CLOSE", title: "Evidence-backed assistance, accountable decisions", body: "The takeaway for this synthetic demo: automate repeatable controls, constrain AI to cited synthesis, and preserve the human decision at the point of operational consequence.", label: "Synthetic demo · no production connectivity", tone: "blue" },
];

function Demo({ launch }: { launch: (i: Incident) => void }) {
  const runs = useExecutableRuns();
  const [tourStarted, setTourStarted] = useState(false);
  const [step, setStep] = useState(0);
  const [remaining, setRemaining] = useState(300);
  const current = demoTourSteps[step];
  useEffect(() => {
    if (!tourStarted || remaining <= 0) return;
    const timer = window.setInterval(() => setRemaining(value => Math.max(0, value - 1)), 1000);
    return () => window.clearInterval(timer);
  }, [tourStarted, remaining]);
  const startTour = () => { setTourStarted(true); setStep(0); setRemaining(300); };
  const resetTour = () => { setTourStarted(false); setStep(0); setRemaining(300); };
  const goToCase = () => { const selected = incidents.find(i => i.id === current.incidentId); if (selected) launch(selected); };
  const minutes = String(Math.floor(remaining / 60)).padStart(2, "0");
  const seconds = String(remaining % 60).padStart(2, "0");
  return <>
    <Header eyebrow="Portfolio demo" title="Five-minute stakeholder tour" text="A presenter-led path through three synthetic outcomes: diagnose, explain, and fail closed." right={<div className="head-actions"><Tag tone="blue">Synthetic only</Tag>{tourStarted ? <button className="secondary" onClick={resetTour}>Exit tour</button> : <button className="primary" onClick={startTour}>Start one-click tour →</button>}</div>} />
    {tourStarted ? <section className="demo-tour" aria-label="Five-minute stakeholder demo tour">
      <div className="demo-tour-top"><div><span className="tour-kicker">STAKEHOLDER DEMO MODE</span><strong>{minutes}:{seconds}</strong><small>remaining · presenter-controlled</small></div><div className="tour-progress">{demoTourSteps.map((item, index) => <button key={item.title} aria-label={`Go to tour step ${index + 1}`} className={index === step ? "active" : index < step ? "visited" : ""} onClick={() => setStep(index)}>{index + 1}</button>)}</div></div>
      <div className="demo-tour-body"><div className={`tour-marker tone-${current.tone}`}>{current.incidentId || "HV"}</div><div><span className="eyebrow">{current.eyebrow}</span><h2>{current.title}</h2><p>{current.body}</p><div className="tour-boundaries"><div><Tag tone="green">Deterministic</Tag><span>Facts, thresholds, and control state are computed in code.</span></div><div><Tag tone="violet">Bounded AI</Tag><span>Drafts stay inside the trusted evidence set and cite their sources.</span></div><div><Tag tone="amber">Human approval</Tag><span>No operational disposition is recorded without an authorised analyst.</span></div></div></div></div>
      <div className="demo-tour-actions">{current.incidentId && <button className="secondary" onClick={goToCase}>Open {current.incidentId} in Workbench ↗</button>}<div><button className="secondary" disabled={step === 0} onClick={() => setStep(value => value - 1)}>Back</button>{step < demoTourSteps.length - 1 ? <button className="primary" onClick={() => setStep(value => value + 1)}>Next: {demoTourSteps[step + 1].label} →</button> : <button className="primary" onClick={resetTour}>Restart tour ↻</button>}</div></div>
    </section> : <><div className="demo-launch-card"><div><span className="tour-kicker">READY FOR WESTPAC CONVERSATION</span><h2>Show the operating model in five minutes.</h2><p>Use the guided tour to make the control boundary legible before opening any individual case. It is deliberately short, synthetic, and presenter-controlled.</p></div><div className="demo-launch-steps">{demoTourSteps.slice(1, 4).map((item, index) => <div key={item.title}><i>0{index + 1}</i><span>{item.incidentId}</span><strong>{item.title.split(" · ")[1]}</strong></div>)}</div></div><div className="scenario-grid">{incidents.map((i,idx) => { const state = runState(i.id, runs[i.id]); return <article key={i.id}><div className="scenario-top"><i>0{idx+1}</i><Tag tone={state.tone}>{state.label}</Tag></div><h2>{i.title}</h2><p>{i.description}</p><div><span>Key judgment</span><strong>{i.guardrail}</strong></div><button className="primary" onClick={() => launch(i)}>{executableIds.has(i.id) ? "Launch executable scenario →" : "Inspect preview →"}</button></article>; })}</div><div className="demo-script"><span>DEMO HANDOFF</span><p>Start the tour for the concise story. Open any case when a stakeholder wants to inspect evidence, approval scope, or the persisted audit trail.</p></div></>}
  </>;
}

export default function Home() {
  const [view, setView] = useState<View>("investigate"); const [incident, setIncident] = useState(incidents[0]); const [persona, setPersona] = useState("Support Analyst"); const [state, setState] = useState<InvestigationState>("ready"); const [audit, setAudit] = useState<string[]>([]);
  const grouped = useMemo(() => nav.reduce<Record<string, typeof nav>>((a,n) => ((a[n.kicker] ||= []).push(n), a), {}), []);
  const open = (i: Incident) => { setIncident(i); setState("ready"); setAudit([]); setView("investigate"); };
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div>HV</div><span><strong>Murex FDE</strong><small>WORKBENCH</small></span></div><div className="bank"><span>FICTIONAL CLIENT</span><strong>HarbourView Bank</strong><small>Capital Markets · Sydney</small></div><nav>{Object.entries(grouped).map(([group,items]) => <div key={group}><span>{group}</span>{items.map(n => <button key={n.view} className={view === n.view ? "active" : ""} onClick={() => setView(n.view)}><i>{({investigate:"⌁",queue:"≡",discover:"⌘",diagnose:"◫",evaluate:"✓",observe:"⌁",govern:"◇",value:"↗",report:"▤",architecture:"⌗",demo:"▷"} as Record<View,string>)[n.view]}</i>{n.label}</button>)}</div>)}</nav><div className="sidebar-foot"><span>DEMO ENVIRONMENT</span><div><i></i> Mock model · Local data</div><small>No production connectivity</small></div></aside><main><div className="topbar"><div className="breadcrumb"><span>HarbourView Bank</span><b>/</b><strong>{nav.find(n => n.view === view)?.label}</strong></div><div className="top-actions"><a className="source-link" href="https://github.com/TheKhozaChain/Murex_FDE" target="_blank" rel="noreferrer">View source ↗</a><button aria-label="Notifications">◌<i></i></button><select aria-label="Current persona" value={persona} onChange={e => setPersona(e.target.value)}><option>Support Analyst</option><option>FDE / Implementation Engineer</option><option>Executive / Programme Sponsor</option></select><div className="user">SL</div></div></div><div className="page">
    {view === "investigate" && (executableIds.has(incident.id) ? <ExecutableInvestigation key={incident.id} incident={incident} selectIncident={setIncident} /> : <Investigation incident={incident} setIncident={setIncident} state={state} setState={setState} audit={audit} setAudit={setAudit} />)}
    {view === "queue" && <Queue open={open} />}{view === "discover" && <Discover />}{view === "diagnose" && <Diagnose />}{view === "evaluate" && <ExecutableEvaluation />}{view === "observe" && <ExecutableObservability />}{view === "govern" && <Govern />}{view === "value" && <Value />}{view === "report" && <Report />}{view === "architecture" && <Architecture />}{view === "demo" && <Demo launch={open} />}
  </div><footer><span>Independent educational simulation · All data and workflows are fictional</span><span>Murex is a trademark of its respective owner · Not affiliated with or endorsed by Murex</span></footer></main></div>;
}
